title = "Ethan Rosenthal"
baseURL = "https://www.ethanrosenthal.com"
tags = ["data science", "machine learning"]
languageCode = "en-US"
config = "config.toml"
theme = "osprey"
canonifyURLS = true
googleAnalytics = "G-BKVZ2X6CBG"
pygmentsUseClasses = true

[markup]
  [markup.highlight]
    style = "github"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[taxonomy]
    tag = "tags"

[permalinks]
    blog = "/:year/:month/:day/:slug/"

[Params]
    headline = "ethan rosenthal"
    subheadline = "data, science, etc"
    author = "Ethan Rosenthal"
    description = ""
    logoBig = "/images/profile.png"
    logoSmall = "/images/profile.png"
    favicon = "favicon.ico"
    opengraphImage = ""
    twitter = "eprosenthal"
    linkedin = "ethanrosenthal"
    github = "EthanRosenthal"
    email = "ethan@ethanrosenthal.com"
    googleTagManager = ""
    highlightJS = true
    copyright = true
    credit = true
    customCSS = false
    cacheBustCSS = false
    cacheBustJS = false
    ajaxFormspree = false


[[menu.main]]
    name = "About"
    url  = "/#about"
    weight = 1

[[menu.main]]
    name = "Blog"
    url  = "/#blog"
    weight = 2

[[menu.main]]
    name = "Links"
    url = "/links"
    weight = 3
