title = "Ethan Rosenthal"
baseURL = "https://ethanrosenthal.com"
tags = ["data science", "machine learning"]
languageCode = "en-US"
config = "config.toml"
theme = "osprey"
canonifyURLS = true
googleAnalytics = "UA-54232305-1"
disableKinds = ["taxonomy", "taxonomyTerm"] # This theme does not currently use "tag" and "category" taxonomies

[permalinks]
    blog = "/:year/:month/:day/:slug/"

[Params]
    headline = "Ethan Rosenthal, PhD"
    subheadline = "Data Science Consulting"
    author = "Ethan Rosenthal"
    description = ""
    logoBig = "/images/profile_pic2.jpg"
    logoSmall = "/images/profile_pic2.jpg"
    favicon = "favicon.ico"
    opengraphImage = "/images/profile_pic2.jpg"
    twitter = "eprosenthal"
    linkedin = "ethanrosenthal"
    github = "EthanRosenthal"
    email = "ethan@ethanrosenthal.com"
    googleTagManager = ""
    highlightJS = true
    copyright = true
    credit = true
    customCSS = false
    cacheBustCSS = false
    cacheBustJS = false
    ajaxFormspree = false


[[menu.main]]
    name = "Services"
    url  = "/#services"
    weight = 1

[[menu.main]]
    name = "About"
    url  = "/#about"
    weight = 2

[[menu.main]]
    name = "Blog"
    url  = "/#blog"
    weight = 3

